#  _____  ______   _
# |  __ \ |  ___| | |
# | |  \/ | |_    | |  _   _
# | | __  |  _|   | | | | | |
# | |_\ \ | |     | | | |_| |
#  \____/ \_|     |_|  \__, |
#                       __/ |
#                      |___/

#Config Version
VERSION: 1.0.0
#Default Config For GFly
GFly_Default:
  #Show a tip about pLayer's flight permission | true/fasle
  Show_Join_Tip: true
  #The tip message: Flight Permission -> Yes
  Join_Tip_Allow_Flight: You Can Fly!
  #The tip message: Flight Permission -> No
  Join_Tip_Not_Allow_Flight: You Can't Fly!
  #Show a tip when player have no permission break blocks in fly
  Not_Break_Blocks_Tip: You can't do this in fly mode!
  #Force all players to cancel flight permission | true/fasle
  Force_Not_Allow_Flight: false
  #Auto add new player's config, setting to false can help reduce the size of the configuration file | true/false
  Auto_Player_Config: true

#Default Config For Every New Player
Each_Player_Default:
  #Allow to fly | true/fasle
  AllowFlight: false
  # Allow to break block(s) when in flight | true/false
  Allow_Break_Blocks: true
  #Allow get damage from others when in flight | true/false
  Allow_Get_Damage: true
  #Allow PVP when in flight | true/false
  Allow_PVP: false
